
server:
  port: 8084
spring:
  cloud:
    gateway:
      routes:
        - id: AUTHENTICATION_SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**   
        - id: DEPARTMENT-SERVICE	
          uri: http://localhost:8081
          predicates:
            - Path=/dep/** 
        - id: EMPLOYEE-SERVICE	
          uri: http://localhost:8082
          predicates:
            - Path=/emp/**   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  tracing:
    sampling:
      probability: 1.0

  