server:
  port: 8060

spring:
  application:
    name: apigateway_app

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Auto-register routes for Eureka services
          lower-case-service-id: true  # Use lowercase service names
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE  # Eureka will resolve this
          predicates:
            - Path=/employee/**
          filters:
            - AuthenticationFilter
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE  
          predicates:
            - Path=/department/**
          filters:
            - AuthenticationFilter
       
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE  # Must match Eureka registration exactly
          predicates:
             - Path=/auth/**
          #filters:
          #  - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true  # Required to fetch service list from Eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"