spring:
  application:
    name: department-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: Jenisha@123
    driver-class-name: com.mysql.cj.jdbc.Driver 
    
server:
  port: 8081
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  tracing:
    sampling:
      probability: 1.0
  
