spring:
  application:
    name: authentication_service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_db
    username: root
    password: Jenisha@123
    driver-class-name: com.mysql.cj.jdbc.Driver 
server:
  port: 8083